services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-trade}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-tradepass}
      POSTGRES_DB: ${POSTGRES_DB:-tradedb}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-trade}"]
      interval: 30s
      timeout: 10s
      retries: 3

  core-app:
    build: ./core-app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
      - POSTGRES_USER=${POSTGRES_USER:-trade}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-tradepass}
      - POSTGRES_DB=${POSTGRES_DB:-tradedb}
      - POSTGRES_HOST=postgres
      - TIMEFRAME=${TIMEFRAME:-15m}
      - SEQ_LENGTH=${SEQ_LENGTH:-60}
    ports:
      - "8501:8501"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./core-app/src:/app/src

volumes:
  postgres_data: